In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out



In [3]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4249],
        [0.3867],
        [0.3867],
        [0.3129],
        [0.3216],
        [0.3562],
        [0.3506],
        [0.3312],
        [0.3138],
        [0.3845]], grad_fn=<SigmoidBackward0>)

In [4]:
model.linear.weight

Parameter containing:
tensor([[-0.1990, -0.0734, -0.3097, -0.3907, -0.2866]], requires_grad=True)

In [5]:
model.linear.bias

Parameter containing:
tensor([0.0386], requires_grad=True)

In [6]:
!pip install torchinfo

In [7]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00