In [1]:
import torch
import torch.nn as nn

In [16]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

**Sequential Container**

In [11]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )


  def forward(self,features):
    out = self.network(features)
    return out

In [17]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4601],
        [0.4601],
        [0.4417],
        [0.4089],
        [0.4114],
        [0.4393],
        [0.4519],
        [0.4103],
        [0.4009],
        [0.4313]], grad_fn=<SigmoidBackward0>)

In [18]:
model.linear1.weight

Parameter containing:
tensor([[ 0.1757, -0.3213, -0.2430,  0.3872,  0.3043],
        [-0.4111, -0.4229,  0.1250,  0.3217,  0.2008],
        [ 0.3397,  0.3746, -0.0027,  0.0032,  0.1877]], requires_grad=True)

In [8]:
model.linear1.bias

Parameter containing:
tensor([-0.2505, -0.0239, -0.0097], requires_grad=True)

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
torch.rand(10,5)

tensor([[0.2743, 0.9864, 0.4353, 0.6523, 0.1591],
        [0.8883, 0.1296, 0.5682, 0.4523, 0.6850],
        [0.1354, 0.7140, 0.0333, 0.4513, 0.0918],
        [0.9264, 0.4064, 0.4836, 0.8601, 0.3409],
        [0.6029, 0.5793, 0.7887, 0.9627, 0.5242],
        [0.2315, 0.3752, 0.4547, 0.6618, 0.3800],
        [0.9139, 0.3674, 0.2388, 0.6926, 0.1751],
        [0.6171, 0.1717, 0.0573, 0.9355, 0.0669],
        [0.4615, 0.7516, 0.4659, 0.8123, 0.8745],
        [0.4985, 0.3573, 0.0429, 0.2595, 0.6485]])