In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 0.29803833,  1.44082695,  0.39061962, ...,  1.28347638,
         1.80705425,  0.7947123 ],
       [ 0.12696943, -1.24908568,  0.22075239, ..., -0.10183605,
        -0.14268445,  0.42520534],
       [ 1.45906334, -0.09592562,  1.43501867, ...,  1.33792098,
         0.57059496,  0.31512766],
       ...,
       [ 0.21390608, -0.88455367,  0.18946105, ...,  0.30801075,
         0.0636629 , -0.04276307],
       [-0.17310225,  0.95478427, -0.22748581, ..., -0.69255989,
        -0.44326917, -0.82215726],
       [-1.30972891, -0.78925119, -1.32390162, ..., -0.68530061,
        -0.25641921, -0.14454343]])

In [9]:
y_train

28     M
421    B
487    M
111    B
389    M
      ..
143    B
142    B
227    B
545    B
234    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,

Numpy arrays to pytorch tensors


In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [22]:
# Defining the model
class MySimpleNN():
  def __init__(self,X):
    # define the weights
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    return torch.sigmoid(z)

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [28]:
# Important parameters
learning_rate = 0.1
epochs = 25

In [31]:
# Training Pipeline
model = MySimpleNN(X_train_tensor)
# define loop epochs time
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)
  # loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)
  # print(loss)
  # backward pass
  loss.backward()
  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  # print loss in each epoch
  print(f'Epoch:{epoch + 1}, Loss: {loss.item()}')

Epoch:1, Loss: 3.474667442848625
Epoch:2, Loss: 3.341611708797784
Epoch:3, Loss: 3.205508641539142
Epoch:4, Loss: 3.067122706802726
Epoch:5, Loss: 2.9240334911560235
Epoch:6, Loss: 2.776881220936361
Epoch:7, Loss: 2.6207395414532066
Epoch:8, Loss: 2.4631420678739766
Epoch:9, Loss: 2.304188908804448
Epoch:10, Loss: 2.1422333360492876
Epoch:11, Loss: 1.9856207789936198
Epoch:12, Loss: 1.834064474126679
Epoch:13, Loss: 1.6868749030728738
Epoch:14, Loss: 1.5493983512499967
Epoch:15, Loss: 1.419089325870976
Epoch:16, Loss: 1.3002425692773425
Epoch:17, Loss: 1.1963838305615508
Epoch:18, Loss: 1.1081111097986693
Epoch:19, Loss: 1.035242790070153
Epoch:20, Loss: 0.976720327847571
Epoch:21, Loss: 0.9307507507810365
Epoch:22, Loss: 0.8951213921647508
Epoch:23, Loss: 0.8675497480211148
Epoch:24, Loss: 0.8459698642407316
Epoch:25, Loss: 0.8287075594619269


In [32]:
model.weights

tensor([[ 0.0377],
        [ 0.3276],
        [ 0.0975],
        [ 0.2567],
        [ 0.2050],
        [ 0.3548],
        [-0.1459],
        [-0.1099],
        [-0.3447],
        [ 0.5168],
        [-0.2308],
        [ 0.4043],
        [ 0.0545],
        [ 0.0830],
        [ 0.0520],
        [-0.3684],
        [ 0.3425],
        [-0.3536],
        [ 0.3287],
        [ 0.4554],
        [ 0.2988],
        [ 0.1957],
        [-0.3211],
        [ 0.2446],
        [ 0.0096],
        [-0.0352],
        [-0.0760],
        [-0.3978],
        [ 0.1123],
        [-0.1974]], dtype=torch.float64, requires_grad=True)

In [33]:
model.bias

tensor([-0.1259], dtype=torch.float64, requires_grad=True)

In [39]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy:{accuracy.item()}')


Accuracy:0.5153893232345581
