In [2]:
import torch
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available
Using GPU: Tesla T4


**CREATING A TENSOR**

In [5]:
# empty function allocates the memory
a = torch.empty(2,3)

In [6]:
type(a)

torch.Tensor

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.rand(2,3)

tensor([[0.7536, 0.7874, 0.3438],
        [0.9999, 0.5078, 0.1269]])

In [10]:
# to make sure each time rand output should be same so use seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# to build custom tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways
print("Using arange -> ",torch.arange(0,10))
# linearly space
print("Using lanspace -> ", torch.linspace(0,10,10))
# identity matrix
print("Using eye -> ",torch.eye(5))
print("Using full -> ",torch.full((3,3),5))

Using arange ->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using lanspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
