In [14]:
import torch
print(torch.__version__)

2.10.0+cu128


In [15]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available
Using GPU: Tesla T4


**Tensor Shapes**

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [17]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[    132850314182016,           361361360, 2338328528881197088],
        [7309940799517582706, 8028075781084312691, 7236287822631739502]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x)
# reason:rand generates the floats so type cast

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

**Tensor Data Types**

In [25]:
# find Data Type
x.dtype

torch.int64

In [26]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
# using to()
x.dtype

torch.int64

In [30]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [31]:
torch.rand_like(x.to(torch.float64))

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)