In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


**Scalar Operations**

In [4]:
x = torch.rand(2,2)
print(x)

tensor([[0.3660, 0.1478],
        [0.3822, 0.7225]])


In [5]:
# addition
print(x+2)
# subtration
print(x-2)
# multiplication
print(x*2)
# division
print(x/3)
# int division
print((x * 100) // 3)
# mod
print((x * 100) % 3)
# power
print(x**2)

tensor([[2.3660, 2.1478],
        [2.3822, 2.7225]])
tensor([[-1.6340, -1.8522],
        [-1.6178, -1.2775]])
tensor([[0.7319, 0.2957],
        [0.7644, 1.4451]])
tensor([[0.1220, 0.0493],
        [0.1274, 0.2408]])
tensor([[12.,  4.],
        [12., 24.]])
tensor([[0.5967, 2.7841],
        [2.2193, 0.2533]])
tensor([[0.1339, 0.0219],
        [0.1461, 0.5221]])


**Element Wise Operation**

In [6]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2409, 0.6583, 0.1106],
        [0.5946, 0.4716, 0.5686]])
tensor([[0.8395, 0.7700, 0.9311],
        [0.8040, 0.3326, 0.4603]])


In [7]:
# add
print(a+b)
# sub
print(a-b)
# multiplication
print(a*b)
# division
print(a/b)
# mod
print(a%b)


tensor([[1.0804, 1.4284, 1.0417],
        [1.3986, 0.8042, 1.0289]])
tensor([[-0.5986, -0.1117, -0.8205],
        [-0.2093,  0.1390,  0.1082]])
tensor([[0.2022, 0.5069, 0.1030],
        [0.4781, 0.1568, 0.2617]])
tensor([[0.2870, 0.8550, 0.1188],
        [0.7396, 1.4181, 1.2350]])
tensor([[0.2409, 0.6583, 0.1106],
        [0.5946, 0.1390, 0.1082]])


In [8]:
c = torch.tensor([1,-2,3,-4])
print(c)

tensor([ 1, -2,  3, -4])


In [9]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [10]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [11]:
d = torch.tensor([1.9,2.3,3.7,4.4])
print(d)

tensor([1.9000, 2.3000, 3.7000, 4.4000])


In [12]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [14]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [15]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [16]:
# clmap defines the range for entire elements in tensor (b/w min and max)
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

**Reduction operation** Mean reducing the entire tensor into single number like array reduce method in js.

In [23]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 2., 3.],
        [2., 2., 6.]])

In [24]:
# sum
print(torch.sum(e))
# sum along columns
print(torch.sum(e,dim=0))
# sum along rows
print(torch.sum(e,dim=1))


tensor(23.)
tensor([10.,  4.,  9.])
tensor([13., 10.])


In [26]:
# mean
print(torch.mean(e))
# mean along col
torch.mean(e,dim=0)

tensor(3.8333)


tensor([5.0000, 2.0000, 4.5000])

In [27]:
# median
print(torch.median(e))
# max and min
print(torch.max(e))
print(torch.min(e))
# product
print(torch.prod(e))

tensor(2.)
tensor(8.)
tensor(2.)
tensor(1152.)


In [28]:
# standard deviation
torch.std(e)

tensor(2.5626)

In [29]:
# variance
torch.var(e)

tensor(6.5667)

In [30]:
# argmax => return the position of the max element
torch.argmax(e)

tensor(0)

In [31]:
# argmin => return the position of the min element
torch.argmin(e)

tensor(1)

**Matrix Operations**

In [32]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[8, 5, 0],
        [4, 8, 6]])
tensor([[7, 7],
        [4, 8],
        [9, 7]])


In [33]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 76,  96],
        [114, 134]])

In [35]:
# dot product
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([3,2,1])
torch.dot(v1,v2)

tensor(10)

In [38]:
# transpose
torch.transpose(f,0,1)

tensor([[8, 4],
        [5, 8],
        [0, 6]])

**Comparison Operations**

In [41]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[1, 6, 5],
        [9, 0, 6]])
tensor([[7, 2, 4],
        [0, 1, 3]])


In [42]:
# greater than
print(i>j)
# less than
print(i<j)
# equal to
print(i==j)
# not equal to
print(i!=j)
# greater than equal to
print(i>=j)
# less than equal to
print(i<=j)

tensor([[False,  True,  True],
        [ True, False,  True]])
tensor([[ True, False, False],
        [False,  True, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False,  True,  True],
        [ True, False,  True]])
tensor([[ True, False, False],
        [False,  True, False]])


**Special functions**

In [43]:
k = torch.randint(size=(2,3),low=0,high=10)
k

tensor([[0, 2, 7],
        [4, 3, 1]])

In [46]:
# log
print(torch.log(k))
# exp
print(torch.exp(k))
# sqrt
print(torch.sqrt(k))
# sigmoid
print(torch.sigmoid(k))
# softmax
print(torch.softmax(k.to(torch.float32),dim=0))

tensor([[  -inf, 0.6931, 1.9459],
        [1.3863, 1.0986, 0.0000]])
tensor([[1.0000e+00, 7.3891e+00, 1.0966e+03],
        [5.4598e+01, 2.0086e+01, 2.7183e+00]])
tensor([[0.0000, 1.4142, 2.6458],
        [2.0000, 1.7321, 1.0000]])
tensor([[0.5000, 0.8808, 0.9991],
        [0.9820, 0.9526, 0.7311]])
tensor([[0.0180, 0.2689, 0.9975],
        [0.9820, 0.7311, 0.0025]])


In [48]:
# relu -> converts the negative value to zero
torch.relu(k)

tensor([[0, 2, 7],
        [4, 3, 1]])