In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


Inplace Operations

In [49]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.7040, 0.6611, 0.3956],
        [0.7120, 0.1752, 0.0124]])
tensor([[0.7106, 0.3485, 0.2822],
        [0.6352, 0.7729, 0.4313]])


In [50]:
# adding m and n ; storing result in m
m.add_(n)

tensor([[1.4146, 1.0097, 0.6777],
        [1.3473, 0.9481, 0.4437]])

In [51]:
m

tensor([[1.4146, 1.0097, 0.6777],
        [1.3473, 0.9481, 0.4437]])

In [52]:
m.relu_()

tensor([[1.4146, 1.0097, 0.6777],
        [1.3473, 0.9481, 0.4437]])

**Copying a tensor**

In [53]:
a = torch.rand(2,3)
a

tensor([[0.2679, 0.5855, 0.5299],
        [0.9333, 0.3758, 0.4462]])

In [54]:
b = a
b

tensor([[0.2679, 0.5855, 0.5299],
        [0.9333, 0.3758, 0.4462]])

In [55]:
a[0][0] = 0
print(a)
print(b)

tensor([[0.0000, 0.5855, 0.5299],
        [0.9333, 0.3758, 0.4462]])
tensor([[0.0000, 0.5855, 0.5299],
        [0.9333, 0.3758, 0.4462]])


In [56]:
print(id(a))
print(id(b))

139651135493760
139651135493760


In [57]:
b=a.clone()
b

tensor([[0.0000, 0.5855, 0.5299],
        [0.9333, 0.3758, 0.4462]])

In [59]:
# now both tensors are refering to the different memory
print(id(a))
print(id(b))

139651135493760
139651134970992
