In [2]:
import torch
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available
Using GPU: Tesla T4


Tensor Operations on GPU

In [4]:
device = torch.device('cuda')
print(device)

cuda


In [6]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.0223, 0.4625, 0.5545],
        [0.6954, 0.3124, 0.7623]], device='cuda:0')

In [7]:
a = torch.rand(2,3)
a

tensor([[0.1381, 0.2935, 0.5475],
        [0.0126, 0.9716, 0.7329]])

In [9]:
# moving an existing tensor to GPU
b = a.to(device)
b

tensor([[0.1381, 0.2935, 0.5475],
        [0.0126, 0.9716, 0.7329]], device='cuda:0')

In [10]:
# now operations will run on gpu
b+5

tensor([[5.1381, 5.2935, 5.5475],
        [5.0126, 5.9716, 5.7329]], device='cuda:0')

**Reshaping Tensors**

In [11]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [13]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
b = torch.rand(2,3,4)
b

tensor([[[0.4827, 0.2492, 0.6709, 0.0019],
         [0.0256, 0.5211, 0.9030, 0.8603],
         [0.8293, 0.4369, 0.6555, 0.1501]],

        [[0.1231, 0.9571, 0.1184, 0.9052],
         [0.6455, 0.5124, 0.9629, 0.2748],
         [0.4443, 0.4300, 0.9509, 0.1075]]])

In [16]:
# permute => adjusting the dimension as per the need
b.permute(2,0,1)

tensor([[[0.4827, 0.0256, 0.8293],
         [0.1231, 0.6455, 0.4443]],

        [[0.2492, 0.5211, 0.4369],
         [0.9571, 0.5124, 0.4300]],

        [[0.6709, 0.9030, 0.6555],
         [0.1184, 0.9629, 0.9509]],

        [[0.0019, 0.8603, 0.1501],
         [0.9052, 0.2748, 0.1075]]])

In [27]:
# typical image size
c = torch.rand(226,226,3)
# unsqueeze => adds the new dimension in the given location
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [32]:
# squeeze => removes the dimension from the given location
d = torch.rand(1,20)
print(d)
d.squeeze(0)

tensor([[0.2860, 0.0809, 0.9281, 0.5847, 0.7525, 0.0694, 0.7310, 0.2857, 0.1306,
         0.5778, 0.1676, 0.1762, 0.3589, 0.3592, 0.6951, 0.7541, 0.0925, 0.1177,
         0.0193, 0.1895]])


tensor([0.2860, 0.0809, 0.9281, 0.5847, 0.7525, 0.0694, 0.7310, 0.2857, 0.1306,
        0.5778, 0.1676, 0.1762, 0.3589, 0.3592, 0.6951, 0.7541, 0.0925, 0.1177,
        0.0193, 0.1895])